### ISSUE TITLE
Did something go wrong with 0.3.5?

### ISSUE THREAD

**Issue by bensmeets** [percolatestudio/publish-counts#27]
Hi, no idea if and how this could be. But starting tonight (after update) my Client won't run (filled with Meteor is undefined, Template is undefined, etc. in the console).

If I remove publish-counts it works again. If i re-add it. It breaks again. Re-installed Meteor, all packages, etc. But still the same behaviour.

When manually adding the package after removing, it says "adding 0.3.5".

Cheers.

p.s. force downgrade to 0.3.4 and it works.

**Comment by dburles** [comment]
Very strange, I've just released 0.3.6, perhaps give that a try.

**Comment by bensmeets** [comment]
Jup, that seemed to do the trick. Not sure what happened, but the "error" had something to do with calling "UI.foo()" instead of "Template.foo()". Weird, because 0.3.5 exactly seemed to change that.

Oh well, fixed and thanks!

**Comment by dburles** [comment]
Great! thanks for letting me know!
