### ISSUE TITLE
Shouldn't there be a difference for count being 0 and counter not existing?

### ISSUE THREAD

**Issue by zimme** [percolatestudio/publish-counts#32]
I was wrong about 35a0eba851b641b9781cc68e5033a8f255276e47 destroying reactivity, it was related to another issue which I've submitted a PR for. #30

However one thing the commit ended up doing was removing the distinction between a counter being 0 and a counter not existing.

I feel there should be a difference.

What are your thoughts about this?

**Comment by dburles** [comment]
I know what you mean but I can't think of any major downside to it. Did you have any examples?

**Comment by zimme** [comment]
For one, the helper will always print 0 making devs assume the counter is working even if it doesn't exist.
Typos won't be as easy to spot as you will still get a 0.

What if you wanna do something different if the counter doesn't exists? as opposed to when the count is 0.

```
if (typeof Counts.get('non-existent') === 'undefined')
  do something else.
// or do somethink only when the counter exists?
if (typeog Counts.get('might exist') !== 'undefined')
  do something with existing counter only even if 0
```

I felt that returning `undefined` or `false` or throwing an error for non existent counters was the better way, giving us the options to hide stuff based on if couter exists/are ready yet.

**Comment by bduddie** [comment]
Agree with @zimme here. In my case, we only want to display the UI component containing the counter value once the data is received from the server. With 35a0eba851b641b9781cc68e5033a8f255276e47, we can't easily tell whether the count is actually 0 or we haven't received the count from the server yet.

**Comment by elie222** [comment]
Also, agree with @zimme

**Comment by boxofrox** [comment]
comments and code reviews on #56 are welcome

**Comment by boxofrox** [comment]
@bduddie , @elie222.  Is the API in #56 satisfactory to your use-case?  I will merge it on Saturday unless you point out any issues or recommendations.
