### ISSUE TITLE
Computations that depend on counters are not reactive.

### ISSUE THREAD

**Issue by psoares** [percolatestudio/publish-counts#35]
Hi,
I'm not sure my problem is an issue or just a bad understanding of how meteor works, but I have a problem using counts. I posted a question on stackoverflow about my problem in case you want to have a look there (http://stackoverflow.com/questions/30263378/how-to-make-a-function-that-uses-counters-to-compute-values-reactively). I'll copy the same here :

Here is what I have :

- On the server :

        Meteor.publish('counters', function() {
            Counts.publish(this, 'searches-thisWeek', UserActions.find({
                $and: [
                    { action: SEARCHES_REGEX },
                    { date : { $gte : moment().startOf('week').toDate()} },
                    { date : { $lt : moment().toDate()} }
                ]
            }));

            Counts.publish(this, 'searches-lastWeek', UserActions.find({
                $and: [
                    { action: SEARCHES_REGEX },
                    { date : { $gte :  moment().subtract(1, 'week').startOf('week').toDate()} },
                    { date : { $lt :  moment().subtract(1, 'week').endOf('week').toDate()} }
                ]
            }));
        });

- On the client :

        Template.dashboard.helpers({
            nbSearchesThisWeek : function() {
                var variation = Counts.get('searches-thisWeek') - Counts.get('searches-lastWeek');
                return {
                    currentValue : Counts.get('searches-thisWeek'),
                    orientation : {
                        sign: (variation > 0) ? '+' : '',
                        class: (variation > 0) ? 'up' : 'down'
                    },
                    variation : variation
                };
            }
        });

- In my template I have a :

        {{getPublishedCount 'searches'}}
This one updates fine. It just gets my "searches" counter and updates anytime the counter changes.

However, I have a template that uses my nbSearchesThisWeek helper, and that one executes fine at startup but never updates when any of the dependent counters change.

So my question is, how and where do I make my nbSearchesThisWeek helper react to the changes on the dependent counters values ? I'm very confused when I read the documentation about Deps, Tracking, and ReactiveVars... I didn't really understand where those things should be used to make my use case work...

Thanks for your help.

Philippe

**Comment by tmeasday** [comment]
Hi @psoares - does the value of the the counter actually change -- it if you go to the browser console and type `Counts.get('searches-thisWeek')` it different (forgetting reactivity for a moment)? 

My guess is the query that you are doing for this week's searches (which has `$lt: now`) is not matching new searches that you make.

**Comment by vacarsu** [comment]
Have you looked into observeChanges? I found it helpful and very easy to use for running functions when data changes. http://docs.meteor.com/#/full/observe_changes

**Comment by jjman505** [comment]
I'm also getting an issue with this. The following counts get published, but they are not reactive.

```
Meteor.publish("pendingReview", function(){
    if(Roles.userIsInRole(this.userId, 'compliance')) {
        var pending = Meteor.users.find({
            $or: [
                {
                    'roles': 'distributor',
                    'profile.status': 'PENDING',
                    'profile.agreedToTOC': true,
                },
                {
                    'roles': 'buyer',
                    'profile.status': 'PENDING',
                },
            ]
        });

        pending = pending.fetch();
        pending = _.filter(pending, function(u) {
          return u.hasAllNeededDocs();
        });

        var pendingDistributors = _.filter(pending, function(u) {
          return _.contains(u.roles, 'distributor');
        });

        var pendingBuyers = _.filter(pending, function(u) {
          return _.contains(u.roles, 'buyer');
        });

        var distributorIds = _.pluck(pendingDistributors, '_id');
        var buyerIds = _.pluck(pendingBuyers, '_id');

        Counts.publish(this, 'remainingDistributors', Meteor.users.find({ _id: { $in: distributorIds } }));
        Counts.publish(this, 'remainingBuyers', Meteor.users.find({ _id: { $in: buyerIds } }));
    }
});
```

**Comment by boxofrox** [comment]
@jjman505, is `var pending = Meteor.users.find(...)` reactive?

You construct a list of `buyerIds` and `distributorIds`.  If those lists don't change, then why would the queries (1) change, and subsequently, why would `remainingBuyers` and `remainingDistributors` change?

```js
// (1)
Meteor.user.find({ _id: { $in: distributorIds } })
Meteor.user.find({ _id: { $in: buyerIds } })
```

**Comment by boxofrox** [comment]
Possible solution for @jjman505.  Untested.  Just conveying the seed of an idea.

You need a reactive way to update `buyerIds`, but without resorting to additional meteor packages, Meteor doesn't allow the Tracker-based reactive code on the server.  So lets fudge it with a memory backed collection populated by an observer.  See [stackoverflow](http://stackoverflow.com/questions/19832455/meteor-create-filters-for-a-collection-server-side-and-store-them-in-a-local-co)

```js

function isBuyer (doc) {
    return 'buyer' === doc.roles;
}

function isDistrib (doc) {
    return 'distributor' === doc.roles;
}

Meteor.publish("pendingReview", function(){
    if(Roles.userIsInRole(this.userId, 'compliance')) {
        var buyers       = new Meteor.Collection(null);
        var distributors = new Meteor.Collection(null);

        var observer = {
            added: function (doc) {
                if (isBuyer(doc))
                    buyers.insert({ _id: doc._id });

                else if (isDistrib(doc))
                    distributors.insert({ _id: doc._id });
            },
            changed: function (oldDoc, newDoc) {
                if (! isBuyer(newDoc)) {
                    buyers.remove(newDoc._id)
                }

                if (! isDistrib(newDoc)) {
                    distributors.remove(newDoc._id);
                }
            },
            removed: function (doc) {
                buyers.remove(doc._id);
                distributors.remove(doc._id);
            }
        }

        // observe changes to users query.
        Meteor.users.find({
            $or: [
                {
                    'roles': 'distributor',
                    'profile.status': 'PENDING',
                    'profile.agreedToTOC': true,
                },
                {
                    'roles': 'buyer',
                    'profile.status': 'PENDING',
                },
            ]
        }).observe(observer);


        var distributorIds = _.pluck(pendingDistributors, '_id');
        var buyerIds = _.pluck(pendingBuyers, '_id');

        Counts.publish(this, 'remainingDistributors', distributors.find({}));
        Counts.publish(this, 'remainingBuyers', buyers.find({}));
    }
});
```

**Comment by tmeasday** [comment]
Please don't write server-side joins yourself! (It's pretty performance critical to not leak observers).

I'd consider looking at something like https://atmospherejs.com/reywood/publish-composite to get this done. But there should be something in the framework that helps you here.

**Comment by boxofrox** [comment]
Where's the server-side join in any code here?  I only see one data pulled from one collection in all examples.  In @jjman505's case, I think he needs to invoke `hasAllNeededDocs` to further filter the query result... oh wait, is a join wrapped up in this function implied?

As for leaking observers, I know too little about Meteor's internals to disagree.  Will pulling the observer out of the `Meteor.publish` callback be sufficient to correct this leak?  e.g. use one observer with global server vars to store the buyer and distributor collections.

**Comment by tmeasday** [comment]
Oh! Sorry @boxofrox I think saw some earlier code in an email notification that did look like it was doing a join. The gist looks sensible.

**Comment by boxofrox** [comment]
This thread has got me thinking about the possibility of allowing users to define their own (sub)observer for publish-counts.  Something like this:

```js
// observer-based callbacks for publish-counts must return a numeric offset
// that will be used to adjust the count. consider this example an identity 
// "count-observer", aka the basic count.
var countObserver = {
  added: function (doc) {
    return 1;  // increment count
  },
  changed: function (oldDoc, newDoc) {
    return 0;  // leave count alone
  },
  removed: function (doc) {
    return -1;  // decrement count
  },
};

Meteor.publish('posts', function () {
  Counts.publish(this, 'posts', Posts.find({}), { observer: countObserver });
});

```

The general idea being, users can filter docs as desired in their own callbacks to decide what to count.  This may provide a universal interface to handle any use-case or more foot-shootin.

Food for thought.  :)

**Comment by jjman505** [comment]
So I tried the example from @boxofrox, with minor changes here: 
https://gist.github.com/jjman505/edd91510eeb8b27d9853

I get the following error:
```
Exception from sub pendingReview id CCtvre3cA73bFozdb TypeError: Cannot read property 'options' of undefined
     at Object.Counts.publish (packages/tmeasday:publish-counts/publish-counts.js:42:1)
     at [object Object]._handler (app/server/publications.js:51:16)
     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
     at [object Object]._.extend._runHandler (packages/ddp/livedata_server.js:950:1)
     at [object Object]._.extend._startSubscription (packages/ddp/livedata_server.js:769:1)
     at [object Object]._.extend.protocol_handlers.sub (packages/ddp/livedata_server.js:582:1)
     at packages/ddp/livedata_server.js:546:1
```

**Comment by boxofrox** [comment]
Oooo.  `cursor._cursorDescription` doesn't exist on a null collection (i.e. `new Meteor.Collection(null)`).

I'll have to figure out what we should do in this case.  Any ideas @tmeasday?

I'm thinking perhaps we should just have a null check and do nothing unless `_cursorDescription` is available?

**Comment by boxofrox** [comment]
@jjman505.  publish-counts-0.7.1 is available.  Upgrade the package and try your example again.

**Comment by jjman505** [comment]
Alright, it appear to be working great, thanks!

**Comment by boxofrox** [comment]
Closing issue since OP found his solution on stackoverflow.  Anyone with related issue is free to open new ticket and link to here.
