### ISSUE TITLE
support numbers for countFromFieldLength

### ISSUE THREAD

**Issue by dohomi** [percolatestudio/publish-counts#36]
Hi Guys,

would you like to support countFromFieldLength on numbers? I just have a usecase where it would be useful. Or is there an approach already? I have a field ```visits:Number```inside of a collection which I would like to count.
Thanks for looking into this
Cheers Dominic

**Comment by tmeasday** [comment]
Hi @dohomi  - I'm confused. Isn't this the way it works already?

**Comment by dohomi** [comment]
Hi @tmeasday 

Out of your docs it seems that the column counts the ```length```of the array and does not make an addition of an integer:
https://github.com/percolatestudio/publish-counts/blob/master/publish-counts.js#L26
Maybe I'm wrong in this case? I have in my column just counts of visits as numbers like 20, 30, 50 and would like to sum this up to a total count of 100.

**Comment by tmeasday** [comment]
Hi @dohomi - oh you are totally correct, I'm sorry.

Yes, we'd accept a PR that added this (with tests etc of course).

**Comment by dohomi** [comment]
Ok, I'll take a look

**Comment by boxofrox** [comment]
FYI, since release 0.4.0, `countFromFieldSum` was merged as `countFromField`.

Closing issue.
