### ISSUE TITLE
countFromField broken in Meteor 1.1.0.2

### ISSUE THREAD

**Issue by boxofrox** [percolatestudio/publish-counts#39]
Meteor 1.1.0.2 does not provide the `fields` argument for the `remove` callback of `cursor.observeChanges`.
According to the Meteor documentation:

> callbacks may have the following functions as properties:
>
> changed(id, fields)
> The document identified by id has changed. fields contains the changed fields with their new values. If a field was removed from the document then it will be present in fields with a value of undefined.
>
> removed(id)
> The document identified by id was removed from the result set.

This breaks a hard requirement for `countFromField` as there is no way to recover the field count lost by the document removal event.

As a result, [Line 52](https://github.com/percolatestudio/publish-counts/blob/master/publish-counts.js#L52) will always throw a TypeError.  In this example, `'count'` is my `countFromField` value.

```
Exception in queued task: TypeError: Cannot read property 'count' of undefined
     at observers.removed (packages/tmeasday:publish-counts/publish-counts.js:52:1)
     ...
```

Unfortunately, we can't fall back to the `changed` callback as it only returns undefined values for the removed fields instead of the previous value.  I think this only leaves maybe three solutions for publish-counts moving forward:

1.  appeal to MDG to (restore?) the fields argument to the `remove` callback of `cursor.observeChanges`, or
2.  use `cursor.observe` instead which provides the old document as an argument to its `removed` callback, or
3.  cache doc ids with counts so publish-counts always knows the count of every document observed (not recommended).

I prefer (2) assuming no existing features are broken by the change.

Here's a sample test case to demonstrate the problem.

```
$ cd /tmp
$ meteor create testunit
$ cd testunit
$ cat <EOF > testunit.js
if (Meteor.isServer) {
  Meteor.startup(function () {
    var Test = new Meteor.Collection('test');

    Test.find({}).observeChanges({
      removed: function (id, fields) {
        if (undefined === fields)
          throw new Error('fields is undefined');
        if (null === fields)
          throw new Error('fields is null');

        console.log('fields is good', fields);
      },
    });

    Test.insert({
      a: {
        b: 1,
        c: 2,
      },
      d: 10,
    });

    Test.remove({});
  });
}
EOF
$ meteor
[[[[[ /tmp/testunit ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000/
Exception in queued task: Error: fields is undefined
     at Test.find.observeChanges.removed (testunit/testunit:8:17)
     at packages/mongo/observe_multiplex.js:183:1
     at Array.forEach (native)
     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
     at Object.task (packages/mongo/observe_multiplex.js:177:1)
     at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
     at packages/meteor/fiber_helpers.js:125:1
^C
$
```

Upon running this test, I observe the "fields is undefined" error is thrown and reported in the console.

Will see about submitting a PR for this as I find time.

**Comment by boxofrox** [comment]
I just noticed that caching is already implemented with the `prev` variable.

**Comment by tmeasday** [comment]
Hi @boxofrox I think this looks great. My one concern would be the switch from `observeChanges` to `observe`. My understanding is that `observe` is going to be less efficient (it involves potentially unnecessary lookups) -- I think this was the rationale behind using `observeChanges` and the `prev` cache, although it's clear there was a bug in the old implementation.

I can see there's a challenge in handling the `changed` event and knowing whether the relevant field has changed in the functional case. But perhaps we should just pass the new set of fields to the function and have a rule that if it returns `null` (or even throws perhaps?) we assume this means that the field hasn't changed? What do you think?

Certainly with these excellent test suites it will be easy to validate each approach :)

**Comment by boxofrox** [comment]
Sorry, it's been long enough since I've made these changes that I'm fuzzy on the details.  Pretty much means I'll say stupid things until I get my head straight.

In terms of efficiency, I think I was looking at it from the other direction in terms of efficient use of space.  My PR sacrifices time instead of space, hence the removal of `prev`.  I think my concern at the time was a cache for partial counts might get out of hand with a sufficiently large collection.  I'm okay with aligning my goal with yours.  I think it'd be trivial to rewrite my PR to rely on `prev` to rollback partial counts.

I don't follow about the `changed` event.  Which function is receiving the set of fields and returning null/throwing?

If you like, I can separate the commit for the test suite into its own PR while we work out the rest.

**Comment by boxofrox** [comment]
After staring at the code for `changed` for 20 minutes or so, I presume the function I asked about is `countFn`.  If so, I don't see much trouble there.  If `prev[id]` is non-zero and the `extraField` is `undefined`, then let `next = 0` and the subsequent `count += next - prev[id]` will proceed as usual.

New question.  What are your thoughts on my addition of the accessor function?  One of its key benefits is support for nested fields.  Given `{ a: {b: {c :5 } } }`, you can count by field `a.b.c`'s value.  I don't know what support Meteor's `observeChanges` has for changes of deep properties in documents.  Reverting my PR to use `observeChanges` may preclude this feature until Meteor makes the change on their end.  I'll need to whip up a test to validate this supposition.

**Comment by tmeasday** [comment]
You know what, thinking about it more, I'm not sure there is a performance impact of using `observe` rather than `observeChanges`.The thing is that the observer is caching this stuff anyway.

I'll ask someone to make sure. I'll get back to you.

I think the accessor function is good. It makes sense to me, apart from the fact that we now can't easily tell if a `change` event is relevant or not (we could before , by checking the changed fields against the key).

PS `observeChanges` like most things in Meteor works at the level of top level properties. So I'm not sure if I'm understanding the question but I think it's fine.

**Comment by boxofrox** [comment]
Re: PS.  I should probably get some rest.  It's only been 12 minutes and I can't recall exactly what the problem with shallow updates was.  Part of my brain probably thought that Meteor might only **detect** changes against top-level properties instead of deep properties, and not report the latter, which seems absurd now that I consider it.

**Comment by tmeasday** [comment]
Right. Well it would be a bug that someone probably would have run into by now :)

**Comment by tmeasday** [comment]
Ok, I think the answer is there's no real performance difference so I think we can go with this..
