### ISSUE TITLE
Counts.publish doesn't work on the atmosphere version. Still need to use publishCount

### ISSUE THREAD

**Issue by elie222** [percolatestudio/publish-counts#45]
Looks like some kind of problem when you pushed to atmosphere. The latest docs say to use Counts.publish, but when I use that, I get an error saying Counts isn't defined.

Looks like the github package isn't in sync with atmosphere.

**Comment by tmeasday** [comment]
Works for me @elie222 - can you provide a reproduction by any chance?

**Comment by elie222** [comment]
Strange. I'll have more of look later. I was using it in a package.

**Comment by tmeasday** [comment]
The package system can be weird if you don't depend on a version.

**Comment by elie222** [comment]
Ah. That must be the problem

**Comment by elie222** [comment]
That was the problem. After depending explicity on @0.4.0, I got the message:
```
tmeasday:publish-counts  upgraded from 0.2.7 to 0.4.0
```
