### ISSUE TITLE
countFromField with tranform doesn't work

### ISSUE THREAD

**Issue by bitomule** [percolatestudio/publish-counts#47]
I'm trying yo use countFromField to publish the number of roles from all the users but this doesn't work. Does publish counts ignore collection transform?
````
Counts.publish(this, 'membersCount',
    	Meteor.users.find({}, { fields: { _id: 1, roles: 1 },transform:function(doc){
			var keys = _.keys(doc.roles);
			doc.rolesCount = keys.length;
			return doc;
		}}),
		{
			countFromField:'rolesCount'
		}
	);
````

I've also tried using a function in countFromField and returning there the count and doesn't work too. I've added logs in both functions and never fire. Any idea?

**Comment by boxofrox** [comment]
The accessor function for `countFromField` was just pulled into master, so if you're working with a release version of publish-counts, this feature isn't available, yet.

The culprit is publish-counts sets which fields are returned by the cursor.
```js
    if ('function' !== typeof extraField) {
      // ensure the cursor doesn't fetch more than it has to
      cursor._cursorDescription.options.fields = {_id: true};         /* Oops, just erased your settings */
      if (extraField)
        cursor._cursorDescription.options.fields[extraField] = true;
    }
```
That's the bad news.

The good news is, you should be able to use `countFromFieldLength: roles` instead.

**Comment by bitomule** [comment]
@boxofrox The issue is that roles is an object, not an array. Using a function for countFromFieldLength is available on published version? If I transform my roles object into an array, should it work or count ignores transform?

**Comment by boxofrox** [comment]
I'm afraid accessor functions are not published, neither for countFromField nor for countFromFieldLength.

Before @tmeasday releases my PR for accessor functions, he asked me to make a few changes to how cursor field limits are handled, so your cursor field options aren't lost (see #40).  I'm working on that now, and hope to have a pull request ready today.  If @tmeasday is happy with it, I expect he'll merge and release.

I'll post a link to the next PR here when it's up.

If you can't wait, you can switch to the `master` branch and try out the accessor functions.  `master` only has 4 commits from my PRs over `release/0.4.0` (see [changelog](https://github.com/percolatestudio/publish-counts/compare/release/0.4.0...master)) and includes comprehensive test units to verify those changes work.
```sh
$ cd path/to/meteor/project
$ mkdir packages
$ git clone git@github.com:percolatestudio/publish-counts.git packages/publish-counts
$ meteor remove tmeasday:publish-counts
$ meteor add tmeasday:publish-counts
```
This will use publish-counts from the `packages/publish-counts` folder, which defaults to the `master` branch after a clone. This is my method for testing my PR commits.

**Comment by boxofrox** [comment]
FYI, release/0.5.0 is published on atmospherejs if you want to give it try.

**Comment by boxofrox** [comment]
BTW, `countFromFieldLength` doesn't enforce working with an array.  If your object has a `length` property, then `countFromFieldLength` will read that property.

**Comment by bitomule** [comment]
Thanks! testing and works exactly as expected. Great work!
