### ISSUE TITLE
bad count with accessor functions when doc updates remove then re-add the count field

### ISSUE THREAD

**Issue by boxofrox** [percolatestudio/publish-counts#51]
Steps to reproduce:

1. create a countByField* with accessor function.  e.g. `{countByField: function (doc) { return doc.a; }}`
2. add a document. e.g. `Posts.insert({_id: 123, a: 5})`
3. update the document without a count field: e.g. `Posts.update(123, {})`
4. update the document with a count field: e.g. `Posts.update(123, {a: 6})`
5. note that `Counts.get()` did not add 6.

PR to follow.

**Comment by tmeasday** [comment]
LGTM.
