### ISSUE TITLE
Split the client / server into 2 files for performance

### ISSUE THREAD

**Issue by chmac** [percolatestudio/publish-counts#65]
Firstly, thanks for taking the hassle out of publishing counts, it's a great service to the meteor community.

I'm assuming that because the `publish-counts.js` file is being loaded on both client and server, that all of its code is minified and shipped to the client. I realise it's not much, but the client only part looks like <20% of the total filesize. If it was 2 files, then I'm assuming meteor would only minify and ship the client part of the code to the browser, instead of the whole file.

A minor optimisation for sure, but probably relatively quick to implement. I'd be happy to submit a pull request if you're open to merging it.

**Comment by tmeasday** [comment]
Sure thing.

**Comment by apendua** [comment]
:+1:

**Comment by chmac** [comment]
Awesome, thanks @boxofrox
