### ISSUE TITLE
How can restart Count?

### ISSUE THREAD

**Issue by jmlv** [percolatestudio/publish-counts#69]
Hey!
I have some publication function, like this:

```js
Meteor.reactivePublish('postsCount', function() {
  if (this.userId) {
    var user = Meteor.users.findOne({
      _id: this.userId
    }, {
      reactive: true
    });

    if (!!user.team) {
      var team = Teams.findOne({
        _id: user.team
      });

      if (team && team.owner === user._id) {
        Counts.publish(this, 'postsCounter', Posts.find({
          $or: [
            {
              owner: user.team,
              shared: true,
              archive: false
            }, {
              owner: user.team,
              shared: false,
              archive: false
            }, {
              owner: this.userId,
              shared: false,
              archive: false
            }
          ]
        }));
      }

      Counts.publish(this, 'postsCounter', Posts.find({
        $or: [
          {
            owner: user.team,
            shared: true,
            archive: false
          }, {
            owner: this.userId,
            shared: false,
            archive: false
          }
        ]
      }));
    }

    Counts.publish(this, 'postsCounter', Posts.find({
      owner: this.userId,
      shared: false,
      archive: false
    }));
  }

  this.ready();
});
```

renaming or removing field 'team' from user record does not trigger update event for counter

*Update 20150920: reformat and add syntax highlighting --boxofrox*

**Comment by jmlv** [comment]
This is two screeshots what i mean
![2015-09-15 16-49-00 mongochef 3t software labs non-commercial license](https://cloud.githubusercontent.com/assets/7571432/9878134/f141dbee-5bc9-11e5-810e-57c45717c9cb.png)
![2015-09-15 16-49-35 mongochef 3t software labs non-commercial license](https://cloud.githubusercontent.com/assets/7571432/9878133/f1340884-5bc9-11e5-98e1-e3afde04ebd1.png)

    console.log(cursor.count());
    Counts.publish(this, 'PostsCounter', cursor);

console.log tells me about changed count, but Counts tells me no

**Comment by boxofrox** [comment]
I don't understand what you're trying to achieve with your example.

When all your `if` block conditions pass, then you redefine one named count three times.  If you need three counters for one user subscription, then give them different names (see #66).

If you left out `else` blocks, please add them and try to keep the code indented so we can read it easily.

Based on the example code provided, two or more counts are dumping their values under one name.  That last counter doesn't appear to be affected by changes to the `team` field.

**Comment by jmlv** [comment]
Tnx for you answer boxofrox. But I am create my counter without this package.
