### ISSUE TITLE
Counts is getting the same number of comments for each post

### ISSUE THREAD

**Issue by adavia** [percolatestudio/publish-counts#70]
Lets say im showing a list of posts with each corresponding number of comments. For some reason i get the same number of comments for each post when ever i add or remove comments. This is happening when i do return Counts.get("comments-count") but it works fine if i do return Comments.find({postId: postId}).count(); 
This is my code so far:

post_item.html
```
<template name="postItem">
  <li>{{name}} <span class="pull-right"> {{commentsCount}}</span></li>
</template>
```

post_item.js
```
Template.postItem.onCreated(function() {
  return this.subscribe('comments', this.data._id);
});

Template.postItem.helpers({
  commentsCount: function() {
    return Counts.get('comments-count'); // This works: Comments.find({postId: this._id}).count(); 
  }
});
```

comments.js
```
Meteor.publish('comments', function(postId) {
  Counts.publish(this, 'comments-count', Comments.find({postId: postId}));
  return Comments.find({postId: postId});
});
```

**Comment by boxofrox** [comment]
I believe this is answered [here](https://github.com/percolatestudio/publish-counts/issues/66#issuecomment-137891179).  Let me know if it doesn't.

**Comment by adavia** [comment]
Excelent. Just what i needed.
