### ISSUE TITLE
How to count documents based on user created documents createdBy field?

### ISSUE THREAD

**Issue by Ajaxsoap** [percolatestudio/publish-counts#73]
Hello,

Posting this as separate issue as requested by @boxofrox .
I have a use case for counting the documents by a user ```createdBy ``` field, to count all the the user (branch users) documents based on the user company. 

I've managed to achieved the counts of documents per company per branch based on user roles with the help of @boxofrox :) Thanks for that!

My requirement is something like this, if the role is ```HQ``` company hq(head office), it should display the document count of its branches.
![branchcount](https://cloud.githubusercontent.com/assets/6571832/10715044/2f0be1e4-7b42-11e5-82d6-516d776b5bfe.png)

What you see on the total enrollments column is actually the total number of documents the company has. I don't know how achieve this requirement, based on @tmeasday , it is not possible at this time.

Do you have any workaround for this?

**Comment by tmeasday** [comment]
Realistically this looks like a Mongo aggregation to me. Do you need the counts to update in real time?

If so I think best way to do it would be subscribe from the client side for each branch.

If not, then I'd suggest simply using a mongo aggregation (way simpler) to get the data and not worry about doing anything fancy.

**Comment by boxofrox** [comment]
This is beyond the scope of publish-counts at this time.  Here's an outline for an alternative.  It's untested.

The basic idea is you keep a global cache of the counts in memory on the server, publish access to the cache, and clients subscribe to it.

It's a fair bit of code to do one thing, and could probably be done with less code using Mongo aggregation.  [1] [2]

[1] https://docs.mongodb.org/manual/core/aggregation-introduction/
[2] https://github.com/meteorhacks/meteor-aggregate

The non-persistent collection may have issues with client-server synchronization as indicated in [3].

[3] https://groups.google.com/forum/#!topic/meteor-talk/-DuOCfYskPU

```js
// server side
(function () {
  // create in-memory cache to store stats in.
  var EnrollmentStats = new Collection('enrollment-stats', {connection: null});   // aka es

  // store one document per company.
  // each document lists branches.
  // each branch list stats (i.e. number of enrollments)

  var inc = function (doc) {
    var selector = {company: doc.company};
    var stats = {};
    stats['branches.' + doc.branch] = 1;    // add 1 to doc.branches.<branch name>

    EnrollmentStats.upsert(selector, { $inc: stats });
  };

  var dec = function (doc) {
    var selector = {company: doc.company};
    var stats = {};
    stats['branches.' + doc.branch] = -1;   // minus 1 from doc.branches.<branch name>

    EnrollmentStats.upsert(selector, { $inc: stats });
  };

  var esObserver = {
    added:    inc,
    changed:  function (newDoc, oldDoc) {
      if (newDoc.company === oldDoc.company && newDoc.branch === oldDoc.branch)
        return;   // company and branch remain the same, count is unaffected

      dec(oldDoc);
      inc(newDoc);
    },
    removed:  dec,
  };

  // attach observer to Enrollments (NOTE: not EnrollmentStats)
  Enrollments.observe(esObserver);


  // publish interface to access stats
  Meteor.publish('enrollment-stats', function () {
    // TODO: adjust query based on user roles as necessary.

    var profile = getUserProfile(this.user_id);   //

    return EnrollmentStats.find({company: profile.company});
  });
})();
```

```js
// client side
var EnrollmentStats = new Collection('enrollment-stats');

Meteor.subscribe('enrollment-stats', 'KRkwBeicgL5ayedGa' /* company id */, function () {
  console.log('enrollment stats', EnrollmentStats.find().fetch());
});
```

**Comment by Ajaxsoap** [comment]
Thanks for this @boxofrox and @tmeasday !

I will try to understand both approach and will let you know what works for me.
