### ISSUE TITLE
countFromField returns collection count rather than the sum of field values

### ISSUE THREAD

**Issue by Pushplaybang** [percolatestudio/publish-counts#74]
trying to return the collection count, and the sum of a field on each doc.

```js
Counts.publish(this, 'clips', Media.find({
    $and: [
      {type: 'clip'},
      {publishedStatus: 'published'}
    ]
  }, {
    fields: {
      _id: 1,
      'stats': 1
    }
  }));
  Counts.publish(this, 'responses', Media.find({
    $and: [
      {type: 'response'},
      {publishedStatus: 'published'}
    ]
  },{
    fields: {
      _id: 1,
      'stats': 1
    }
  }));

  Counts.publish(this, 'votesDown', Media.find({
    'stats.votesDown': { $exists: true }
  }, {
    fields: {
      _id: 1,
      'stats.votesDown': 1
    }
  },{
    countFromField: function (doc) {
      return doc.stats.votesDown;
    }
  }));
```

This only return s the total count for the collection.

**Comment by boxofrox** [comment]
As I understand it, you're trying to create two collection counts, `clips` and `responses`, and one sum, `votesDown`.

Are you saying all three counts return the total count for the collection?

Why do you need to include `stats` in the field specifier for the first two counts?  Keep in mind that `clips` and `responses` are basic counts, which means they only count documents, only require `_id` to do so, and thus modify the field specifier to only include `_id`.  So `'stats': 1` isn't used.

**Comment by Pushplaybang** [comment]
Hey @boxofrox 

thanks for the incredibly snappy reply, but the idiot is outside the box on this one.   Theres a very small syntactical error above, that resulted in some odd behaviour.   Not sure if its possible but would be great to fail loudly on that.  You're absolutely right about the extra fields above, totally unnecessary.

All thats needed to fix the above (other than moving a few superfluous fields) is to close the `.find` parenthesis after the fields declaration, rather than after the last object containing the `countFromField` function.

the correct version : 

```js

Counts.publish(this, 'votesDown', Media.find({
    'stats.votesDown': { $exists: true }
  }, {
    fields: {
      _id: 1,
      'stats.votesDown': 1
    }
  // not closing the .find here resulted in the error above
  }),{
    countFromField: function (doc) {
      return doc.stats.votesDown;
    }
  });

```

Thanks for the awesome package, this made knocking out a little dashboard incredibly easy.  cheers!

**Comment by boxofrox** [comment]
Not sure how we could fail loudly in this case.  The last argument to `Counts.publish` is optional, and if it's absorbed into the Meteor query, there really isn't a reliable way for us to detect that in publish counts.  Maybe the Meteor group could be more stringent and warn when `Collection.find` is given extraneous properties.

About the only fix I can think of is to create a separate function for `Counts.publish` that requires all four parameters.

```js
Counts.publish4 = function (context, name, cursor, options) {
    if (undefined === options)
        throw new Error("Counts.publish4: Argument Error: options not defined");
    Counts.publish(context, name, cursor, options);
}
```

It's pretty trivial to implement, so I'm inclined to let developers write it themselves if they need/desire it.

Glad this was an easy fix, though.  Cheers.

Closing without prejudice.
