### ISSUE TITLE
Question about the sample code

### ISSUE THREAD

**Issue by derwaldgeist** [percolatestudio/publish-counts#78]
In example 1, the JS part is as follows:
```js
Meteor.publish('publication', function() {
  Counts.publish(this, 'name-of-counter', Posts.find());
  return Posts.find();
});
```
whereas the CoffeeScript states:
```js
Meteor.publish 'publication', ->
  Counts.publish this, 'name-of-counter', Posts.find()
  return undefined    # otherwise coffeescript returns a Counts.publish
                      # handle when Meteor expects a Mongo.Cursor object.
```
I assume that both samples should return an undefined value, to illustrate publishing "just" a counter?

I deducted this from the sample located under the explanation of ```noReady```, where I learned that I have to provide the ```noReady``` flag if I also want to return a Cursor, not just a Counter. Or did I get that wrong, and the code in example 1 is correct, i.e. the ```noReady``` isn't needed in this case? If so, I would like to understand why.

**Comment by boxofrox** [comment]
You are right.  I accepted portions of PR #72 to improve the docs, and inadvertently missed that `return Posts.find();` in my reversion commit.  I'll get that removed.  Thanks!

**Comment by boxofrox** [comment]
Just to clarify, here's what the examples are supposed to be.

##### JavaScript
```js
Meteor.publish('publication', function() {
  Counts.publish(this, 'name-of-counter', Posts.find());
});
```

##### Coffeescript
```coffeescript
Meteor.publish 'publication', ->
  Counts.publish this, 'name-of-counter', Posts.find()
  return undefined    # otherwise coffeescript returns a Counts.publish
                      # handle when Meteor expects a Mongo.Cursor object.
```

**Comment by derwaldgeist** [comment]
Fine, thanks. So I infer that I have to add the ```noReady``` flag if I want to return another cursor as well, right? I'm asking because I did not do this so far.

**Comment by dburles** [comment]
@derwaldgeist that's right

**Comment by derwaldgeist** [comment]
Ok, thanks for this additional info!
